### ISSUE TITLE
text-rendering: optimizeLegibility 讓 Chrome resized 後瀏覽變 lag

### ISSUE THREAD

**Issue by ccwang002** [pycontw/pycontw2016#118]
謝謝 @concise 的回報與解決方法整理。

### 如何重現問題

1. 使用桌機版的 Google Chrome (48.0.2564.109 64bit) 打開官網任何一頁（例如 <https://tw.pycon.org/2016/zh-hant/events/keynotes/>）
2. 調整字型大小 (Cmd +/- or Ctrl +/-)
3. 繼續瀏覽網站，CPU 使用率上升而且變 lag

看相關的討論在 Android 系統上可能也會有 lag 的情況，再請大家測測看 。

### 解決方法

拿掉 CSS 這一行就不會 lag

```scss
// main.scss:30
body {
      // ...
      text-rendering: optimizeLegibility !important; 
      // ...
}
```

### 問題補充

- Safari, Firefox 看起來沒有問題。
- From <https://marco.org/2012/11/15/text-rendering-optimize-legibility>,

  > There are actually significant, effectively fatal performance problems (such as 30-second loading delays, or longer) on mobile devices when using optimizeLegibility

- [CSS-Tricks](https://css-tricks.com/almanac/properties/t/text-rendering/) 上有關於 `text-rendering` 的使用與討論
- 這行 code 是加在 d989691，看起來是跟字型設定時一起放進去的
